import type { BusinessCase } from "@/lib/types";

export const businessCases: BusinessCase[] = [
  {
    id: "product-stripe-tax",
    title: "Stripe Tax module launch strategy",
    company: "Stripe",
    year: 2021,
    scenario: "Expanded a payments platform into tax compliance for internet businesses.",
    pack: "Product",
    tags: ["platform", "compliance", "module", "enterprise", "launch"],
    budget: 500000,
    timeline: "12 months",
    decision: "Ship a focused tax automation module to solve a recurring merchant pain.",
    outcome: "Created a higher-value product surface beyond payments.",
    lesson: "A strong product extension starts from a painful workflow adjacent to the core product."
  },
  {
    id: "product-notion-ai",
    title: "Notion AI launch",
    company: "Notion",
    year: 2023,
    scenario: "Embedded AI writing and knowledge workflows inside an existing workspace.",
    pack: "Product",
    tags: ["ai", "workspace", "productivity", "activation", "collaboration"],
    budget: 300000,
    timeline: "6 months",
    decision: "Add AI as a native workflow layer instead of a separate tool.",
    outcome: "Strengthened retention and monetization across existing users.",
    lesson: "AI features work best when they reduce friction in an already frequent workflow."
  },
  {
    id: "product-figma-collaboration",
    title: "Figma collaboration expansion",
    company: "Figma",
    year: 2016,
    scenario: "Made browser-native multiplayer design collaboration central to the product.",
    pack: "Product",
    tags: ["collaboration", "browser", "design", "team", "workflow"],
    budget: 250000,
    timeline: "18 months",
    decision: "Prioritize real-time collaboration over local-file parity.",
    outcome: "Created a differentiated wedge against incumbent design tools.",
    lesson: "A product can win by changing the collaboration model, not only by matching features."
  },
  {
    id: "product-slack-pmf",
    title: "Slack product-market fit validation",
    company: "Slack",
    year: 2013,
    scenario: "Turned an internal communication tool into a team collaboration product.",
    pack: "Product",
    tags: ["pmf", "team", "communication", "retention", "activation"],
    budget: 200000,
    timeline: "9 months",
    decision: "Validate with teams that had intense internal communication pain.",
    outcome: "High retention and organic team expansion became the growth signal.",
    lesson: "Early PMF is visible through repeated team usage and pull from adjacent teams."
  },
  {
    id: "startup-airbnb-growth",
    title: "Airbnb early growth",
    company: "Airbnb",
    year: 2009,
    scenario: "Built supply and trust in a new peer-to-peer lodging marketplace.",
    pack: "Startup",
    tags: ["marketplace", "growth", "trust", "supply", "wedge"],
    budget: 80000,
    timeline: "12 months",
    decision: "Focus on high-density city launches and improve listing quality manually.",
    outcome: "Improved conversion and unlocked repeatable city expansion.",
    lesson: "Marketplace growth often starts with manual quality work before automation."
  },
  {
    id: "startup-dropbox-mvp",
    title: "Dropbox MVP cold start",
    company: "Dropbox",
    year: 2007,
    scenario: "Validated cloud file sync demand before building the full product.",
    pack: "Startup",
    tags: ["mvp", "cold-start", "video", "validation", "demand"],
    budget: 50000,
    timeline: "3 months",
    decision: "Use a demo video to prove demand before full-scale engineering.",
    outcome: "Waitlist demand validated the product thesis.",
    lesson: "A startup can test demand with a clear artifact before heavy build-out."
  },
  {
    id: "startup-canva-platform",
    title: "Canva from design tool to platform",
    company: "Canva",
    year: 2015,
    scenario: "Expanded from simple design creation into templates, collaboration, and ecosystem.",
    pack: "Startup",
    tags: ["platform", "templates", "collaboration", "international", "growth"],
    budget: 400000,
    timeline: "24 months",
    decision: "Broaden the wedge into a design platform for non-designers.",
    outcome: "Scaled from a tool into a horizontal creative operating system.",
    lesson: "A clear underserved user can support a platform strategy when workflows repeat."
  },
  {
    id: "startup-uber-expansion",
    title: "Uber market expansion",
    company: "Uber",
    year: 2011,
    scenario: "Scaled a city-by-city transportation marketplace.",
    pack: "Startup",
    tags: ["marketplace", "city-launch", "operations", "supply", "timing"],
    budget: 600000,
    timeline: "18 months",
    decision: "Repeat a local launch playbook with dense supply and demand operations.",
    outcome: "Rapid geographic expansion created category leadership.",
    lesson: "Operational playbooks matter when expansion depends on local liquidity."
  },
  {
    id: "marketing-dollar-shave-club",
    title: "Dollar Shave Club viral launch",
    company: "Dollar Shave Club",
    year: 2012,
    scenario: "Used a sharp launch video to create direct-to-consumer subscription demand.",
    pack: "Marketing",
    tags: ["viral", "dtc", "video", "subscription", "brand"],
    budget: 4500,
    timeline: "1 month",
    decision: "Use humor and a direct value proposition to break category inertia.",
    outcome: "Generated massive awareness and early subscription growth.",
    lesson: "A clear wedge and memorable creative can outperform large media spend."
  },
  {
    id: "marketing-duolingo-flywheel",
    title: "Duolingo growth flywheel",
    company: "Duolingo",
    year: 2020,
    scenario: "Built social content and product loops into an always-on growth engine.",
    pack: "Marketing",
    tags: ["growth", "social", "retention", "flywheel", "brand"],
    budget: 120000,
    timeline: "12 months",
    decision: "Lean into distinctive social personality and product habit loops.",
    outcome: "Expanded brand awareness while reinforcing daily engagement.",
    lesson: "The best marketing flywheels reinforce the product behavior they promote."
  },
  {
    id: "marketing-allbirds-dtc",
    title: "Allbirds DTC brand strategy",
    company: "Allbirds",
    year: 2016,
    scenario: "Built a direct-to-consumer footwear brand around simplicity and sustainability.",
    pack: "Marketing",
    tags: ["dtc", "brand", "sustainability", "positioning", "community"],
    budget: 250000,
    timeline: "9 months",
    decision: "Anchor the brand around comfort, materials, and environmental clarity.",
    outcome: "Created strong category differentiation and early customer advocacy.",
    lesson: "DTC brands need a simple reason to believe, not only performance media."
  },
  {
    id: "marketing-hubspot-inbound",
    title: "HubSpot inbound marketing category creation",
    company: "HubSpot",
    year: 2009,
    scenario: "Turned educational content into a B2B acquisition engine.",
    pack: "Marketing",
    tags: ["b2b", "content", "inbound", "pipeline", "category"],
    budget: 150000,
    timeline: "18 months",
    decision: "Educate the market and own the inbound category narrative.",
    outcome: "Built repeatable organic demand and sales pipeline.",
    lesson: "Category marketing compounds when content, product, and sales use the same language."
  },
  {
    id: "hiring-netflix-density",
    title: "Netflix talent density strategy",
    company: "Netflix",
    year: 2009,
    scenario: "Prioritized high talent density and freedom-and-responsibility culture.",
    pack: "Hiring",
    tags: ["talent-density", "culture", "seniority", "performance", "team"],
    budget: 1000000,
    timeline: "24 months",
    decision: "Hire and retain high-performing senior talent rather than scale headcount quickly.",
    outcome: "Created a culture optimized for judgment and speed.",
    lesson: "Hiring quality can be a strategy when the operating model supports autonomy."
  },
  {
    id: "hiring-basecamp-small-team",
    title: "Basecamp small team philosophy",
    company: "Basecamp",
    year: 2010,
    scenario: "Maintained a small, senior team with constrained scope.",
    pack: "Hiring",
    tags: ["small-team", "scope", "remote", "senior", "efficiency"],
    budget: 350000,
    timeline: "12 months",
    decision: "Avoid over-hiring and protect product focus.",
    outcome: "Sustained profitability and calm operations.",
    lesson: "Not hiring can be the right decision when scope discipline is stronger leverage."
  },
  {
    id: "hiring-google-process",
    title: "Google structured hiring process",
    company: "Google",
    year: 2004,
    scenario: "Built structured interviews, calibration, and hiring committees.",
    pack: "Hiring",
    tags: ["process", "interview", "calibration", "scale", "quality"],
    budget: 800000,
    timeline: "18 months",
    decision: "Standardize hiring signals to support quality at scale.",
    outcome: "Improved consistency while scaling technical hiring.",
    lesson: "Hiring systems need calibration when the organization scales decision volume."
  },
  {
    id: "hiring-github-remote",
    title: "GitHub remote-first engineering hiring",
    company: "GitHub",
    year: 2014,
    scenario: "Expanded engineering hiring beyond a single geography.",
    pack: "Hiring",
    tags: ["remote", "engineering", "distributed", "talent", "process"],
    budget: 450000,
    timeline: "12 months",
    decision: "Use remote work to access stronger specialized talent pools.",
    outcome: "Built distributed engineering capacity before it became mainstream.",
    lesson: "Remote hiring works when documentation, ownership, and communication systems are explicit."
  },
  {
    id: "investment-yc-framework",
    title: "YC early-stage investment framework",
    company: "Y Combinator",
    year: 2005,
    scenario: "Invested in early teams using founder quality, speed, and market insight.",
    pack: "Investment",
    tags: ["early-stage", "founder", "speed", "market", "portfolio"],
    budget: 125000,
    timeline: "3 months",
    decision: "Back teams with high learning velocity and clear user pain.",
    outcome: "Created a repeatable early-stage portfolio model.",
    lesson: "At early stage, founder learning speed can outweigh complete market proof."
  },
  {
    id: "investment-sequoia-thesis",
    title: "Sequoia sector selection logic",
    company: "Sequoia Capital",
    year: 2010,
    scenario: "Used market maps and category timing to concentrate conviction.",
    pack: "Investment",
    tags: ["thesis", "market", "category", "timing", "conviction"],
    budget: 5000000,
    timeline: "24 months",
    decision: "Build conviction around large markets before selecting specific winners.",
    outcome: "Supported concentrated bets in durable technology categories.",
    lesson: "Investment quality improves when market timing and company quality are evaluated together."
  },
  {
    id: "investment-a16z-enterprise",
    title: "a16z enterprise investment strategy",
    company: "Andreessen Horowitz",
    year: 2013,
    scenario: "Backed enterprise software companies with network and go-to-market support.",
    pack: "Investment",
    tags: ["enterprise", "gtm", "software", "network", "scale"],
    budget: 3000000,
    timeline: "18 months",
    decision: "Invest where enterprise adoption and founder-market fit can compound.",
    outcome: "Built a strong enterprise software portfolio thesis.",
    lesson: "Capital plus go-to-market support can change the risk-return profile."
  },
  {
    id: "investment-softbank-vision",
    title: "SoftBank Vision Fund concentration lesson",
    company: "SoftBank",
    year: 2017,
    scenario: "Deployed large checks into category leaders with aggressive growth expectations.",
    pack: "Investment",
    tags: ["growth", "concentration", "risk", "capital", "valuation"],
    budget: 10000000,
    timeline: "36 months",
    decision: "Use capital scale to accelerate market leadership.",
    outcome: "Produced mixed outcomes and highlighted valuation and governance risk.",
    lesson: "Large capital deployment increases the cost of being wrong on timing and governance."
  },
  {
    id: "content-red-bull-media",
    title: "Red Bull media house strategy",
    company: "Red Bull",
    year: 2007,
    scenario: "Built an owned media engine around extreme sports and lifestyle.",
    pack: "Content",
    tags: ["owned-media", "brand", "video", "community", "distribution"],
    budget: 1000000,
    timeline: "24 months",
    decision: "Invest in content as a brand-owned distribution asset.",
    outcome: "Created durable brand association and global content reach.",
    lesson: "Content strategy compounds when the brand can own a distinctive cultural territory."
  },
  {
    id: "content-netflix-originals",
    title: "Netflix originals content bet",
    company: "Netflix",
    year: 2013,
    scenario: "Moved from licensed catalog to original programming.",
    pack: "Content",
    tags: ["originals", "subscription", "retention", "data", "portfolio"],
    budget: 100000000,
    timeline: "24 months",
    decision: "Commit to original content to improve differentiation and retention.",
    outcome: "Strengthened the subscription moat and global brand.",
    lesson: "Original content can be strategic when it improves retention and pricing power."
  },
  {
    id: "content-morning-brew",
    title: "Morning Brew newsletter growth",
    company: "Morning Brew",
    year: 2018,
    scenario: "Scaled a daily business newsletter through referral loops and voice.",
    pack: "Content",
    tags: ["newsletter", "referral", "voice", "audience", "cadence"],
    budget: 75000,
    timeline: "12 months",
    decision: "Use a consistent voice and referral mechanics to grow daily readership.",
    outcome: "Built a highly engaged business audience.",
    lesson: "Cadence and voice matter when content becomes a habit product."
  },
  {
    id: "custom-amazon-prime",
    title: "Amazon Prime strategic bundle",
    company: "Amazon",
    year: 2005,
    scenario: "Bundled shipping benefits into a membership program.",
    pack: "Custom",
    tags: ["bundle", "membership", "retention", "commerce", "strategy"],
    budget: 5000000,
    timeline: "18 months",
    decision: "Trade short-term shipping cost for long-term customer frequency.",
    outcome: "Increased retention, purchase frequency, and ecosystem leverage.",
    lesson: "A strategic bundle works when one benefit changes customer behavior across the system."
  },
  {
    id: "custom-microsoft-cloud",
    title: "Microsoft cloud-first strategic shift",
    company: "Microsoft",
    year: 2014,
    scenario: "Shifted operating priority from Windows-first to cloud-first and cross-platform.",
    pack: "Custom",
    tags: ["strategy", "cloud", "platform", "enterprise", "transformation"],
    budget: 10000000,
    timeline: "36 months",
    decision: "Reorient resources and culture around Azure and cloud services.",
    outcome: "Repositioned the company for enterprise cloud growth.",
    lesson: "Major strategic decisions require resource reallocation, not only messaging."
  },
  {
    id: "custom-adobe-subscription",
    title: "Adobe Creative Cloud subscription transition",
    company: "Adobe",
    year: 2012,
    scenario: "Moved from perpetual software licenses to subscription cloud.",
    pack: "Custom",
    tags: ["subscription", "pricing", "cloud", "transition", "retention"],
    budget: 3000000,
    timeline: "24 months",
    decision: "Accept short-term revenue disruption to build recurring revenue.",
    outcome: "Created a stronger SaaS business model and recurring customer relationship.",
    lesson: "Business model transitions need clear migration paths and investor communication."
  }
];
